export const SET_DETAIL_ID = 'detail/SET_DETAIL_ID';
export const RECEIVE_DETAIL_POST = 'detail/RECEIVE_DETAIL_POST';
export const RESET_DETAIL_STATE = 'detail/RESET_DETAIL_STATE';
export const LOADING_DETAIL_COMPLETE = 'detail/LOADING_DETAIL_COMPLETE';
export const SET_CURRENT_DETAIL_DELETED = 'detail/SET_CURRENT_DETAIL_DELETED';

// COMMENT CONSTANTS
export const LOADING_COMMENTS_COMPLETE = 'detail/LOADING_COMMENTS_COMPLETE';
export const RECEIVE_COMMENTS = 'detail/RECEIVE_COMMENTS';
export const RECEIVE_DELETED_COMMENT = 'detail/RECEIVE_DELETED_COMMENT';
export const RECEIVE_NEW_COMMENT = 'detail/RECEIVE_NEW_COMMENT';
export const RECEIVE_NEW_COMMENT_SCORE = 'detail/RECEIVE_NEW_COMMENT_SCORE';
export const SET_COMMENT_SORT_METHOD = 'detail/SET_COMMENT_SORT_METHOD';
export const GET_COMMENT_TO_EDIT = 'detail/GET_COMMENT_TO_EDIT';
export const REMOVE_COMMENT_TO_EDIT = 'detail/REMOVE_COMMENT_TO_EDIT';
export const RECEIVE_EDITED_COMMENT = 'detail/RECEIVE_EDITED_COMMENT';
