export const SET_DETAIL_ID = 'detail/SET_DETAIL_ID';
export const RECEIVE_DETAIL_POST = 'detail/RECEIVE_DETAIL_POST';
export const RESET_DETAIL_STATE = 'detail/RESET_DETAIL_STATE';
export const LOADING_DETAIL_COMPLETE = 'detail/LOADING_DETAIL_COMPLETE';
export const LOADING_COMMENTS_COMPLETE = 'detail/LOADING_COMMENTS_COMPLETE';
export const RECEIVE_COMMENTS = 'detail/RECEIVE_COMMENTS';
export const SET_CURRENT_DETAIL_DELETED = 'detail/SET_CURRENT_DETAIL_DELETED';
